export const INIT_MAP = 'INIT_MAP';
export const SET_MAPVIEW_LOAD_ERROR = 'SET_MAPVIEW_LOAD_ERROR';
export const SET_MAPVIEW_READY = 'SET_MAPVIEW_READY';
export const FETCHING_LAYER_INFO = 'FETCHING_LAYER_INFO';
export const LAYER_INFO_RECEIVED = 'LAYER_INFO_RECEIVED';
export const TOGGLE_VISIBLE_LAYER = 'TOGGLE_VISIBLE_LAYER';
